version: '3.0'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    env_file:
      - .env
    networks:
      - jibin
  test-db:
    image: postgres:13
    ports:
      - 5435:5432
    env_file:
      - .env.test.local
    networks:
      - jibin
networks:
  jibin: